### ISSUE TITLE
Getting location with high accuracy taking time more than 4 mins 

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [apache/cordova-plugin-geolocation#119]
let getOptions = { enableHighAccuracy: true };
    this.geolocation.getCurrentPosition(getOptions).then(position => {
 //code to use location
});

Device : Nokia 6(Android Oreo), iPhone 6 (iOS 11) 

version information
"cordova-plugin-geolocation": "^4.0.1",
 "ionic-angular": "3.9.2",

**Comment by GPlay97** [comment]
I have the same issue. Seems to happen only sometimes. Sometimes it resolves in a few milliseconds / a second, sometimes it takes a minute or longer to resolve. The callback is just not executed.

**Comment by shokry055** [comment]
same here i takes more than 3 minutes 
or return code 3 TO

**Comment by janpio** [comment]
@Gurjit-ONEBCG Nokia 6 and iOS 6 doesn't make sense. Do you mean Android 6 maybe?
@GPlay97 What platform and device are your experiences with?
@shokry055 What platform and device? What does `return code 3 TO` mean?

**Comment by shokry055** [comment]
Time out @janpio

**Comment by carliblaz** [comment]
Well I have the same problem, if I check the logs:

11-16 11:28:17.404  3420 21768 I GCoreUlr: No valid location reports to store
11-16 11:28:18.365 20227 20554 D GeolocationPlugin: We are entering execute
11-16 11:28:23.382 20227 20554 D GeolocationPlugin: We are entering execute
11-16 11:28:28.418 20227 20554 D GeolocationPlugin: We are entering execute
11-16 11:28:32.525  3420 19568 I GCoreUlr: Filtering location: Location[g 45.XXXXXX,13.XXXXXX acc=3 et=+22h11m35s905ms alt=68.50113677978516 vel=0.07393644 mock {Bundle[{mockLocation=true}]}]

But Response is not OK :(

**Comment by janpio** [comment]
"same problem" as who? Original poster said that "Getting location with high accuracy taking time more than 4 mins " - what you posted took 15 seconds.

**Comment by carliblaz** [comment]
Ye it took 15s for triggering error with no response, there is one missing line there, when successfully get location:

11-16 13:04:38.453  3420  6966 I GCoreUlr: Successfully inserted 1 locations

**Comment by UlisesCeca** [comment]
No solution for this yet?

**Comment by janpio** [comment]
@carliblaz What device and OS version are you using?
@UlisesCeca What problem exactly are you referring to? Until now there is no clear report with all data in this issue, so it is hard to solve anything.

**Comment by breautek** [comment]
GPS features is something I heavily use in my apps and in my experience there are two things that can effect slow/non-existent GPS updates. 

**1. User Settings**
On most android versions, the user may have location mode set "battery saving" -- which makes it so the phone requires an internet connection because it only uses wifi & mobile networks to determine location. Or "Device Only", which means the phone must connect to satellites to obtain a location. From a cold fix, it can take 10-15 minutes even in good conditions on a decent device before you start seeing stable GPS updates. The best location setting the phone can be in is "High Accuracy" mode (not to be confused with the api's `highAccuracy` option), which allows the phone to use any number of strategies to obtain a GPS update as quickly as possible. Note that this is a user setting that is outside the control of the app, however I'm sure there are plugins that allows you to open up the appropriate settings screen for the user. I've seen other apps do it.

**2. Poor Environment**
Even with the phone has high accuracy enabled in their location settings. Being in a poor environment can hinder the ability to receive GPS events, or will cause received updates to have inaccurate results. The perfect environment to have stable GPS outsides is outside away from buildings, in clear skies weather. My work office is in a basement of a large building. If I require good accurate GPS events in my testing, I literally cannot do the test at my desk. No joke, if I have to I'd have to take my test device outside of the building and walk around in the parking lot. Alternatively I use a simulator where I have the ability to manually simulate GPS events as if they were coming from the GPS hardware. I'd also like to note that this issue is not exclusive to Cordova. Any app, whether it be Google Maps, or something else that shows your location all exhibit location troubles when I'm in my workplace building.

I hope this information helps.

**Comment by peterpan666** [comment]
I solved it by increasing the timeout value to `30000`...

**Comment by breautek** [comment]
Closing due to lack of response.
