### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by BilalAdhi** [apache/cordova-plugin-geolocation#136]
Is this plugin works offline (Without Internet)?

If yes then how to force the plugin to run offline (Without Internet)?

My code is not working Offline, I just copied the docs code below.

this.geolocation.getCurrentPosition().then((resp) => {
 // resp.coords.latitude
 // resp.coords.longitude
}).catch((error) => {
  console.log('Error getting location', error);
});

**Comment by BilalAdhi** [comment]
Can anyone please reply me?

**Comment by breautek** [comment]
Using the GPS without having a mobile/wifi connection available will result your device relying solely on GPS satellites. It can take a really long time to receive a "GPS Fix" to the satellites. Even in perfect conditions, it can take upwards of 10-15 minutes for an average phone to get a satellite fix. Note that once, the phone has received the satellite fix, gps updates will become much more stable. The satellite positions will be cached, so the next time the GPS requires a fix, in theory should be a lot quicker from a "cold" startup. Note that this doesn't have anything to do with the library or the phone itself. This is simply how GPS satellites and hardware work.

Ideal conditions is being outside, clear weather, open skies (no tall buildings/mountains). Things taht can interfere with GPS signals is being in large buildings, poor/stormy weather, lots of concrete objects in the way limiting the "sky visibility",  etc. The following documents may explain why it takes so long to start up better than I can:
https://en.wikipedia.org/wiki/Time_to_first_fix
https://gpslogger.app/gps-fix-details.html

The reason GPS works quickly when internet access is available is because of "A-GPS" (Assisted-GPS) which completely skips the requirement to look for & connect to several satellites. So obviously, if possible, it's best to have an online connection, but if offline support is necessary then you'll need to be prepared for a lengthy period of time before the phone can begin receiving GPS events.

I realize this is probably not an answer you were expecting, but I hope this information helps provide you a better understanding of GPS technology and in turn, help you make informed decisions in your app development.

**Comment by breautek** [comment]
Background updates are not currently supported. The main challenge with this is that not all devices allows webview javascript to run in the background.
