### ISSUE TITLE
Android - Notification and icon when getting location

### ISSUE THREAD

**Issue by UlisesCeca** [apache/cordova-plugin-geolocation#150]
Hello.

In Android 8 only. I am getting a notification with an icon which isn't the icon of my App. Is it possible to change this icon and the texts or remove the notification?

I am calling the method to get my position like this:

`this.geolocation.getCurrentPosition({ enableHighAccuracy: true, timeout: 1000, maximumAge: 1000 }).then(...`

And this is the icon I am talking about (the one about fusedlocationprovider):

![pic](https://user-images.githubusercontent.com/23300072/55820517-908d9600-5afb-11e9-8e80-072304bdc02a.jpg)

Is there any way to do this?

Thanks!

**Comment by UlisesCeca** [comment]
Up

**Comment by breautek** [comment]
I don't believe Cordova is responsible for this because the plugin itself actually does nothing related to geolocation other than checking and requesting the appropriate permissions. The entire location retrieving process is all completely handled by the browser itself.

With that being said, I'd suspect that you have another plugin installed that is causing this issue. Showing the output of `cordova plugin list` may be helpful.

**Comment by kPlusPlus** [comment]
error 3, timeout
only first time working and then stop stop stop and never go
HORROR

**Comment by breautek** [comment]
If there is no response in the next few days I'll be closing this ticket.
