### ISSUE TITLE
Geolocation logs wrong lat and  long on ionic 4 

### ISSUE THREAD

**Issue by Mahdibenamor** [apache/cordova-plugin-geolocation#172]
# Bug Report
 
## Problem
  when using watchPosition() function : it gives positions but those positions are wrong ,  i have tested on chrome and firefox but the some problem i v got , i think that issue is related to cordova not to ionic 

### Command or Code
 this.subscription= this.geolocation.watchPosition(options).subscribe((data)=>{

              this.latitude=data.coords.latitude;
              this.longitude=data.coords.longitude;
              this.findme=true;
              console.log(this.longitude,this.latitude);

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
There are several reasons why you might be seeing poor/inaccurate GPS results, and I go into more detail in my [gist](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e).

Most of the time this is caused by device configurations not having AGPS enabled (so it doesn't use mobile networks, wifi, networks, etc to assist in your location finding), and being in a poor environment where it is difficult to communicate with GPS satellites, such as a basement or large buildings.

If you see inaccurate GPS point, I would suggest looking at the `accuracy` value on the GPS point. The `accuracy` value represents radius in meters around the GPS point of which the GPS is confident that you're actual location is within the radius. So in otherwords if the accuracy value reads high like 60, then the GPS point could in theory be up to 60 meters off of your real location and is likely inaccurate and perhaps unusable depending on your use case. If the `accuracy` value reads low such as `5` meters, then you can probably trust that GPS point to be pretty accurate.

What can you do about it?

If you haven't, you can try setting the `enableHighAccuracy` option to `true`, which will make the GPS more aggressive in finding more accurate location, and it will trigger updates more frequently (usually maximum 1 event per second). 

Outside of `enableHighAccuracy` option being enabled, there isn't much you can do as this is usually an environment problem.

**Comment by Mahdibenamor** [comment]
Thank you very much for these full details, mister breautek, it turns out that the problem is related to both the environment and the network, I have selected to enable "high resolution", it is true that I have good accuracy from the previous one, it turns out that the problem is related to the network. Sorry for not closing the case.
