### ISSUE TITLE
Ionic 3 getCurrentPosition getting wrong coords and timestamp on Android 8

### ISSUE THREAD

**Issue by greatstart** [apache/cordova-plugin-geolocation#179]
# Bug Report

## Problem
when using getCurrentPosition, it getting wrong coords and timestamp. The timestamp return is one week ago.

### Environment, Platform, Device
It happens on Android 8

**Comment by breautek** [comment]
When this occurs, does it also have a high ( >30) accuracy value? These could be erroneous GPS events that come from the GPS receiver itself, which usually happens when the GPS receiver "wakes up". In these cases, it's usually expected the developer to listen and filter the GPS that doesn't make sense based on their application.

Additionally, this may occur if you use the `maximumAge` option as that will return cached GPS points, however you'll need a really high value to get a GPS point a week old...

**Comment by breautek** [comment]
Closing as stale.
