### ISSUE TITLE
Fused Location Provider notification on Android

### ISSUE THREAD

**Issue by steosoft** [apache/cordova-plugin-geolocation#183]
I'm using your library and it works very well but I have question. 
After calling ```watchPosition``` method Android 9.0 shows notification "Fused Location Provider" with default Android icon. Is there any way to change this name/text and icon?

**Comment by breautek** [comment]
Apologies for lack of a timely response, but I don't believe that is coming from this plugin.

This plugin don't even provide a geolocation implementation for android, it simply just handles the native permissions. The geolocation implementation is the browser implementation.

The fuse location provider may be coming from another plugin, or maybe even another app.

**Comment by steosoft** [comment]
Thanks for your answer.
But notification "Fused Location Provider" is definitely from this app and plugin. It shows when I start app (I call ```watchPosition``` just after start) and disappears when I exit from app.

**Comment by breautek** [comment]
In order to provide more insight we will need to know more information about your environment, including cordova version, cordova-android version, and all plugins that is installed. Android OS version and device used may also be helpful. The following commands will show all the versions for cordova.

```
cordova -v
cordova platform ls
cordova plugin ls
```

**Comment by breautek** [comment]
Closing due to staleness.
