### ISSUE TITLE
cordova-plugin-geolocation does not work in android phone (SDK 6.0.0)

### ISSUE THREAD

**Issue by chongfei111** [apache/cordova-plugin-geolocation#196]
this is code in cordova-plugin-geolocation plugin code (package.json)!
  "engines": {
    "cordovaDependencies": {
      "3.0.0": {
        "cordova-android": ">=6.3.0"
      },
      "5.0.0": {
        "cordova": ">100"
      }
    }
  },

Why this supports only from 6.3.0?

**Comment by breautek** [comment]
It doesn't, it supports anything equal to or greater than 6.3.0.

Why it doesn't support less than 6.3.0? See https://github.com/apache/cordova-plugin-compat. Pre 6.3.0 required this dependency to handle permissions. Permission management has been since added to the core framework, which was added in 6.3.0, hence the requirement.

Despite it supporting as low as 6.3.0, you should be using cordova-android@8 for a number of reasons, with the largest one it supports targeting API 28, which is a requirement for deploying to the google play store.

Hope this answers your question. If you have any other questions, I invite you to join our [slack](http://slack.cordova.io/) for support style questions such as this one.
