### ISSUE TITLE
Add support for Huawei devices which don't have Google Play Services

### ISSUE THREAD

**Issue by spinninghamster** [apache/cordova-plugin-geolocation#218]
# Feature Request

## Motivation Behind Feature
Huawei has removed Google Play Services from their newest models. I believe this is causing major issues with many apps which require them.

## Feature Description
Add support for Huawei services. See:
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001050140246

**Comment by breautek** [comment]
Does Huawei devices still use the chrome-based webview? We don't have a native android geolocation implementation. We simply delegate to the webview for geolocation. The only thing this plugin does do for android is manage permissions. Because of this, I don't think this plugin has a Google Play Services requirement.

If you have a Huawei device available for testing, I think it's worth while creating a test app that simply uses the `cordova-plugin-geolocation` plugin to help us determine if any action is actually required. If this is an indeed an issue, it looks like Huawei has their own [cordova plugin](https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/location-integrating-cordova-sdk-v4) already built for using their own Location APIs

**Comment by jcesarmobile** [comment]
Closing since there wasn't a response.

But as breautek said, the plugin doesn't require Google Play Services for getting the location, it doesn't even have any native code other than for requesting permissions, it relies on the WebView geolocation implementation, which doesn't use the Fused Location Provider, so shouldn't require Google Play Services.
