### ISSUE TITLE
android.hardware.location.gps added twice in androidManifest

### ISSUE THREAD

**Issue by piernik** [apache/cordova-plugin-geolocation#222]
I have two plugins that uses location. Yours and Google Maps:  https://github.com/mapsplugin/cordova-plugin-googlemaps

This way there are two  tags `<uses-feature android:name="android.hardware.location.gps" />` in `AndroidManifest.xml` file :/

Tried adding 
```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/uses-feature[@android:name='android.hardware.location.gps']" xmlns:android="http://schemas.android.com/apk/res/android">
            <uses-feature android:name="android.hardware.location.gps" />
        </edit-config>
```
to config.xml file but it is not helping. How to solve it?

**Comment by apri23** [comment]
I also have the same problem. build error. any solutions?

**Comment by breautek** [comment]
Unfortunately the two plugins conflicts because they and this plugin boht uses `<config-file>` directive which **always** inserts the contents into the target which obviously leads into duplicates.

In order to use this plugin alongside with google maps plugin, a hook will probably have to be made to dedupe the android manifest entry.

And `after_prepare` hook to scan and remove one occurence `<uses-feature android:name="android.hardware.location.gps" />` should do it (along with any other duplicates caused by the same issue).

Manually modifying the project will work, but there are many actions that may cause the project to be re-prepared/reconstructed and you'll have to remember to manually fix it each time that happens, whereas the hook can automate that for you.
